config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/demichie/OpenPDAC-11:
      branch: main
      repo: https://github.com/demichie/OpenPDAC-11/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/demichie/OpenPDAC-11 git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-amaranth-whale.sh
        container: qc.acc_craggy-corn-magpie
  QC.Doc:
    repos:
      github.com/demichie/OpenPDAC-11 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-tan-dormouse.sh
        container: qc.doc_squirrely-rose-wallaby
      github.com/demichie/OpenPDAC-11 git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-purple-weasel.sh
        container: qc.doc_slimy-fuchsia-gorilla
      github.com/demichie/OpenPDAC-11 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-plum-chow.sh
        container: qc.doc_breezy-flax-tamarin
  QC.Lic:
    repos:
      github.com/demichie/OpenPDAC-11 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-lemon-malamute.sh
        container: qc.lic_clammy-red-lemur
  QC.Sec:
    repos:
      github.com/demichie/OpenPDAC-11 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-magnolia-audemer.sh
        container: qc.sec_cloudy-sapphire-chinook
  QC.Sty:
    repos:
      github.com/demichie/OpenPDAC-11 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-crimson-gar.sh
        container: qc.sty_seedy-buff-tapir
  QC.Ver:
    repos:
      github.com/demichie/OpenPDAC-11 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-lavender-mastiff.sh
        container: qc.ver_squeaky-chestnut-capuchin
timeout: 5400
